{
  "name": "aa-attendance-backend",
  "builds": [
    {
      "src": "package.json",
      "use": "@render/node-builder"
    }
  ],
  "env": {
    "NODE_ENV": "production",
    "PORT": {
      "fromService": { "type": "web", "name": "aa-attendance-backend" }
    },
    "DATABASE_URL": {
      "fromService": { "type": "pserv", "name": "aa-attendance-db" }
    }
  }
}
